social_media/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/<int:user_id>/', views.dashboard, name='dashboard'),

]

social_media/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.all_post, name='all_post'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('add-post/<int:user_id>/', views.add_post, name='add_post'),
    path('post-delete/<int:user_id>/<int:post_id>/', views.delete_post, name='post_delete'),
    path('post-edit/<int:user_id>/<int:post_id>/', views.edit_post, name='post_edit'),
]

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('posts.urls', namespace='posts')),
]

social_media/templates/inc/messages.html
{% if messages %}
{% for message in messages %}
<p class="alert alert-{{ message.tags }}">{{ message }}</p>
{% endfor %}
{% endif %}

social_media/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a href=" {% url 'posts:all_post' %}" class="nav-item nav-link active">Home</a>
        {% if not request.user.is_authenticated %}
        <a href=" {% url 'account:login' %}" class="nav-item nav-link active">Login</a>
        <a href=" {% url 'account:register' %}" class="nav-item nav-link active">Register</a>
        {% else %}
        <a href=" {% url 'account:logout' %}" class="nav-item nav-link active">Logout</a>
        <a href=" {% url 'account:dashboard' request.user.id %}" class="nav-item nav-link active">Panel</a>
        {% endif %}
    </div>
</nav>