social_media/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/<int:user_id>/', views.dashboard, name='dashboard'),

]

social_media/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.all_post, name='all_post'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('add-post/<int:user_id>/', views.add_post, name='add_post'),
    path('post-delete/<int:user_id>/<int:post_id>/', views.delete_post, name='post_delete'),
    path('post-edit/<int:user_id>/<int:post_id>/', views.edit_post, name='post_edit'),
]

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('posts.urls', namespace='posts')),
]

social_media/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='upost')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} ____ {self.body[:30]}'

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.created.year, self.created.month, self.created.day, self.slug])

    objects = models.Manager()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcommect')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

    objects = models.Manager()

    class Meta:
        ordering = ('-created',)

social_media/posts/forms.py
from django import forms
from .models import Post, Comment


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-control col-md-6'
            })
        }

social_media/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import AddPostForm
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from .forms import EditPostForm, CommentForm


# Create your views here.

def all_post(request):
    posts = Post.objects.all()
    return render(request, 'posts/all_posts.html', {'posts': posts})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, created__year=year, created__month=month, created__day=day, slug=slug)
    comments = Comment.objects.filter(post=post, is_reply=False)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            form = CommentForm()
    else:
        form = CommentForm()
    return render(request, 'posts/post_detail.html', {'post': post,
                                                      'comments': comments,
                                                      'form': form})


@login_required
def add_post(request, user_id):
    if user_id == request.user.id:
        if request.method == 'POST':
            form = AddPostForm(request.POST or None)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.user = request.user
                new_post.slug = slugify(form.cleaned_data['body'][:30])
                new_post.save()
                messages.success(request, 'Your post submitted', 'success')
                return redirect('account:dashboard', user_id)
        form = AddPostForm()
        return render(request, 'posts/add_posts.html', {'form': form})
    else:
        return redirect('posts:all_post')


@login_required
def delete_post(request, user_id, post_id):
    if request.user.id == user_id:
        Post.objects.get(pk=post_id).delete()
        messages.success(request, 'your post deleted successfully', 'success')
        return redirect('account:dashboard', user_id)
    else:
        return redirect('posts:all_post')


@login_required
def edit_post(request, user_id, post_id):
    if request.user.id == user_id:
        post = get_object_or_404(Post, id=post_id)
        if request.method == 'POST':
            form = EditPostForm(request.POST, instance=post)
            if form.is_valid():
                edited_post = form.save(commit=False)
                edited_post.slug = slugify(form.cleaned_data['body'][:30])
                edited_post.save()
                messages.success(request, 'Your post edited successfully', 'success')
                return redirect('account:dashboard', user_id)
        else:
            form = EditPostForm(instance=post)
        return render(request, 'posts/edit_posts.html', {'form': form})
    else:
        return redirect("posts:all_post")

social_media/posts/templates/posts/add_posts.html
{% extends 'base.html' %}

{% block content %}
<form method = "post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="POST" class="btn btn-success">
</form>

{% endblock %}

social_media/posts/templates/posts/all_posts.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <p class="card-header"><a href="{% url 'account:dashboard' post.user.id %}">{{ post.user }}</a></p>
            <p class="card-body"><a href="{{ post.get_absolute_url }}"> {{ post.body }}</a></p>
        </div>
    {% endfor %}
{% endblock %}

social_media/posts/templates/posts/edit_posts.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Post" class="btn btn-success">
</form>
{% endblock %}

social_media/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated and request.user.id == post.user.id %}
<a href="{% url 'posts:post_delete' post.user.id post.id %}">Delete post</a>
<a href="{% url 'posts:post_edit' post.user.id post.id %}">Edit post</a>
{% endif %}
<p><a href="{% url 'account:dashboard' post.user.id %}">{{ post.user }} </a> | {{ post.created|date:'j/m/Y' }}</p>
<p> {{ post.body }}</p>
<hr>
{% if request.user.is_authenticated %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Send">
</form>
{% else %}
<p>login for sending comment <a href="{% url 'account:login' %}">Login</a></p>
{% endif %}
Comments : {{comments.count}}
{% for comment in comments %}
<div class="card bg-dark text-white">
    <p class="card-header">{{ comment.user }}</p>
    <p class="card-body">{{ comment.body }}</p>
    {% for reply in comment.rcomment.all %}
    <p class="bg-primary m-5 p-2 text-white">{{ reply.user }} <br> {{ reply.body }}</p>
    {% endfor %}
</div><br>
{% empty %}
<p>There is no comment</p>
{% endfor %}
{% endblock %}